name: Continuous Integration

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v2

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y libx11-dev libxext-dev libxrender-dev libglu1-mesa-dev libgl1-mesa-dev

      - name: Build Linux binary
        run: zig build example

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: tree-simple-linux
          path: zig-out/bin/tree-simple

      - name: Build Windows binary
        run: zig build example -Dtarget=x86_64-windows-gnu -p zig-out-windows

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: tree-simple-windows
          path: zig-out-windows/bin/tree-simple.exe
